#pragma once
#include "typedefs.h"

typedef enum {
	TOKEN_EOF, TOKEN_ERROR,

	TOKEN_IDENTIFIER,
	TOKEN_STRING,
	TOKEN_NUMBER,

	TOKEN_LOCAL, TOKEN_FUNCTION, TOKEN_RETURN, TOKEN_IF, TOKEN_THEN, TOKEN_ELSE, TOKEN_ELSEIF,
	TOKEN_END, TOKEN_WHILE, TOKEN_DO, TOKEN_REPEAT, TOKEN_UNTIL, TOKEN_FOR, TOKEN_IN,
	TOKEN_BREAK, TOKEN_NIL, TOKEN_TRUE, TOKEN_FALSE, TOKEN_AND, TOKEN_OR, TOKEN_NOT,

	TOKEN_TYPE,

	TOKEN_LPAREN, TOKEN_RPAREN,
	TOKEN_LBRACE, TOKEN_RBRACE,
	TOKEN_LBRACK, TOKEN_RBRACK,

	TOKEN_COMMA, TOKEN_DOT, TOKEN_COLON, TOKEN_SEMICOLON,

	TOKEN_PLUS, TOKEN_MINUS,
	TOKEN_STAR, TOKEN_SLASH,
	TOKEN_PERCENT, TOKEN_CARET,
	TOKEN_HASH,
	
	TOKEN_EQ, TOKEN_EQ_EQ,
	TOKEN_NOT_EQ,
	TOKEN_LT, TOKEN_LTEQ,
	TOKEN_GT, TOKEN_GTEQ,

	TOKEN_DOT_DOT,
	TOKEN_DOT_DOT_DOT,
	TOKEN_ARROW,
	TOKEN_PIPE,
} TokenKind;

typedef struct {
	TokenKind kind;
	const char *start;
	u64 length;
	u64 line;

	const char *text;
} Token;
